// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7rtsxIRbOucIaprRxe1xnyE7bQuOW0D0',
    appId: '1:658176889574:web:aaff81571e5100b12a2127',
    messagingSenderId: '658176889574',
    projectId: 'simtengu-flutter',
    authDomain: 'simtengu-flutter.firebaseapp.com',
    databaseURL: 'https://simtengu-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'simtengu-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxDOiAiuFbo-Z_cHXev6QW1SWBzX8P2tY',
    appId: '1:658176889574:android:36be6246d169fd592a2127',
    messagingSenderId: '658176889574',
    projectId: 'simtengu-flutter',
    databaseURL: 'https://simtengu-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'simtengu-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhmb5Ig2zy5xgKdB85dFb6DqTYk8C9uSs',
    appId: '1:658176889574:ios:c3b332049b368a8c2a2127',
    messagingSenderId: '658176889574',
    projectId: 'simtengu-flutter',
    databaseURL: 'https://simtengu-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'simtengu-flutter.appspot.com',
    androidClientId: '658176889574-6igb1m6n79317erqrhgrt6pftvm2k899.apps.googleusercontent.com',
    iosClientId: '658176889574-ep6fs4g5amcdtcla8ahdaurg5p0cvp2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhmb5Ig2zy5xgKdB85dFb6DqTYk8C9uSs',
    appId: '1:658176889574:ios:586995cc1806e8952a2127',
    messagingSenderId: '658176889574',
    projectId: 'simtengu-flutter',
    databaseURL: 'https://simtengu-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'simtengu-flutter.appspot.com',
    androidClientId: '658176889574-6igb1m6n79317erqrhgrt6pftvm2k899.apps.googleusercontent.com',
    iosClientId: '658176889574-3l86bh2i8a0qcu9b596n3c18hjdrsv69.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApplication.RunnerTests',
  );
}
